#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.5ubuntu1
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/30-0-google-crosextra-caladea-fontconfig.conf 20130214-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/62-google-crosextra-caladea-fontconfig.conf 20130214-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.d/30-0-google-crosextra-caladea-fontconfig.conf 20130214-2\~ -- "$@"
# End automatically added section
