#!/bin/sh
set -e
# Automatically added by dh_fortran_mod/0.14
# May be installed multiple times for different canoncomp
multiarch="aarch64-linux-gnu"
base="gfortran-mod-15"
cmplr="gfortran-8"
canoncomp="gfortran-8"

if test ! -d /usr/lib/$multiarch/fortran/$base ; then
   rm -f /usr/lib/$multiarch/fortran/$cmplr
   rm -f /usr/lib/$multiarch/fortran/$canoncomp
fi

if test -d /usr/lib/$multiarch/fortran/$base ; then
  ( cd /usr/lib/$multiarch && rmdir --ignore-fail-on-non-empty --parents fortran/$base )
fi

# Delete broken old symlinks
find /usr/lib/$multiarch -xtype l -delete
# End automatically added section
# Automatically added by dh_fortran_mod/0.14
# May be installed multiple times for different canoncomp
multiarch="aarch64-linux-gnu"
base="gfortran-mod-15"
cmplr="gfortran-9"
canoncomp="aarch64-linux-gnu-gfortran-9"

if test ! -d /usr/lib/$multiarch/fortran/$base ; then
   rm -f /usr/lib/$multiarch/fortran/$cmplr
   rm -f /usr/lib/$multiarch/fortran/$canoncomp
fi

if test -d /usr/lib/$multiarch/fortran/$base ; then
  ( cd /usr/lib/$multiarch && rmdir --ignore-fail-on-non-empty --parents fortran/$base )
fi

# Delete broken old symlinks
find /usr/lib/$multiarch -xtype l -delete
# End automatically added section
