#!/bin/sh
set -e
# Automatically added by dh_fortran_mod/0.15
# May be installed multiple times for different canoncomp
multiarch="aarch64-linux-gnu"
base="gfortran-mod-15"
canoncomp='gfortran-8'

# clear cruft from old bug if present
rm -f /usr/lib/$multiarch/fortran/$base/$base

mkdir -p /usr/lib/$multiarch/fortran/$base
if ! test -x /usr/lib/$multiarch/fortran/$canoncomp ; then
  ln -sf /usr/lib/$multiarch/fortran/$base /usr/lib/$multiarch/fortran/$canoncomp
fi

# Update old dirs
if test -d  /usr/lib/$multiarch/fortran/flang-mod-33 ; then
  mkdir -p /usr/lib/$multiarch/fortran/flang-mod-34
  mv /usr/lib/$multiarch/fortran/flang-mod-33/* /usr/lib/$multiarch/fortran/flang-mod-34
  rmdir /usr/lib/$multiarch/fortran/flang-mod-33
fi
# End automatically added section
# Automatically added by dh_fortran_mod/0.15
# May be installed multiple times for different canoncomp
multiarch="aarch64-linux-gnu"
base="gfortran-mod-15"
canoncomp='aarch64-linux-gnu-gfortran-9'

# clear cruft from old bug if present
rm -f /usr/lib/$multiarch/fortran/$base/$base

mkdir -p /usr/lib/$multiarch/fortran/$base
if ! test -x /usr/lib/$multiarch/fortran/$canoncomp ; then
  ln -sf /usr/lib/$multiarch/fortran/$base /usr/lib/$multiarch/fortran/$canoncomp
fi

# Update old dirs
if test -d  /usr/lib/$multiarch/fortran/flang-mod-33 ; then
  mkdir -p /usr/lib/$multiarch/fortran/flang-mod-34
  mv /usr/lib/$multiarch/fortran/flang-mod-33/* /usr/lib/$multiarch/fortran/flang-mod-34
  rmdir /usr/lib/$multiarch/fortran/flang-mod-33
fi
# End automatically added section
