#!/bin/sh

set -e

if test "$1" = "remove"; then
    if test -x /usr/sbin/update-binfmts; then
        update-binfmts --package llvm-10-runtime \
            --remove llvm-10-runtime.binfmt /usr/bin/lli-10 || true
        if test -f /var/lib/binfmts/llvm-10.binfmt; then
            # Purge old file
            update-binfmts --package llvm-10-runtime \
                --remove llvm-10.binfmt /usr/bin/lli-10 || true
        fi
    fi
fi



